alert("hello");
document.write("hello");
typeof("true");
typeof(123);
typeof("123");
prompt("what is your name");
var name="angela";
name="super";
alert(name);
document.write(name);
var yourname = prompt("what is your name?");
alert("my name is "+name+"wwelome to my course"+yourname+"!");
var n=3;
var nn=5;
var nnn=n;
n=nn;
nn=nnn;
alert(n);
alert(nn);
